name: deploy infrastructure
on:
  push:
    branches:
      - main
jobs:
  run-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./infra"

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-central-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: aws s3 ls

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        run: terraform fmt -check -diff -recursive
        continue-on-error: true

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -no-color -out tfplan

      - name: Terraform Apply
        run: terraform apply -input=false tfplan
